name: Attendace
description: Company Attendance


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  location: ^5.0.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  device_info_plus: ^9.1.1
  awesome_dialog: ^3.2.0
  url_launcher: ^6.2.4
  local_auth: ^2.1.8
  device_information: ^0.0.4
  dartz: ^0.10.1
  get_it: ^7.6.7
  rename: ^3.0.1
  google_fonts: ^6.1.0
  animate_do: ^3.3.1
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  firebase_core: ^2.24.2
  onesignal_flutter: ^3.5.1
  restart_app: ^1.2.1
  cached_network_image: ^3.3.1
  buttons_tabbar: ^1.3.8
  flutter_lints: ^3.0.1
  syncfusion_flutter_datepicker: ^24.1.47
  file_picker: ^6.1.1
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7


dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

