name: Attendace
description: Company Attendance


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  device_info_plus: ^9.1.2
  awesome_dialog: ^3.2.0
  url_launcher: ^6.2.5
  device_information: ^0.0.4
  dartz: ^0.10.1
  get_it: ^7.6.7
  rename: ^3.0.1
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  buttons_tabbar: ^1.3.8
  flutter_lints: ^3.0.1
  syncfusion_flutter_datepicker: ^24.2.8
  file_picker: ^6.1.1
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7


dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

